# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1021e3c0519bfd6452ae7bd2533cd91830c26a692bc3fe88c5ccac8485f4a012ac435bb8d5e2094e1335dd038afe52a7a2ad9a6e3c752a379162cbf723c96af

test:
  secret_key_base: 151ddd99aadf723151439d7e4a30f4fd56722e852f9076294684fd369c4614547cffbbe845f8bdca2454d1be87733a85ca129f8edb62584ca25a7d6b3715f70a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
