# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4c5e177bde599016ae2de4d50072f58f4b9f15d778a36da6b4d154b98ef0d2511f0fc734b3b80fc10cdbf7473d43bce57a07c762720b5126924e8e045a66b5f

test:
  secret_key_base: d656abc93b7db843c39b3d750349259d98ed9d4d7ae5da1c8e5501fd079375e795daa483a1bfd4a9f76deade22649d202540f32c175f46773a5015579c476cd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
